
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import SideBarComponent from "@/Components/sidebar/SideBarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <aside className="fixed h-screen">
            <SideBarComponent />
        </aside>
        <main>
            <section>
                {children}
            </section>
        </main>
        </body>
        </html>
    );
}
